services:

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
      . TZ=Europe/Madrid
    ports:
      - "8200:80"
    volumes:
      - ./abs/audiobooks:/audiobooks
      - ./abs/podcasts:/podcasts
      - ./abs/config:/config
      - ./abs/metadata:/metadata
